#!/usr/bin/env python3
from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "dbworkload"
OUTPUT = ROOT / "CODEMAP.md"

LAYER_NOTES = {
    "dbworkload/cli/main.py": "Typer CLI entrypoint. Parses run options, builds connection info, and dispatches command handlers.",
    "dbworkload/cli/util.py": "Typer subcommands under `dbworkload util`; delegates behavior to command implementations.",
    "dbworkload/cli/dep.py": "Shared CLI parameter declarations and command epilog.",
    "dbworkload/connection.py": "Shared connection info container used across CLI parsing and command runtime.",
    "dbworkload/commands/run.py": "Workload runtime command implementation: starts supervisors/workers, manages schedules, reports stats.",
    "dbworkload/commands/util.py": "Utility command implementations for CSV/YAML generation, charting, stub generation, and CSV merging.",
    "dbworkload/commands/convert.py": "Experimental PL to PL/pgSQL conversion workflow using local or remote LLM providers.",
    "dbworkload/commands/prompts.py": "Prompt templates used by the conversion workflow.",
    "dbworkload/utils/common.py": "Shared helpers for runtime imports, stats aggregation, Prometheus publishing, DDL parsing, and URI handling.",
    "dbworkload/utils/simplefaker.py": "YAML-driven fake data generator used by the CSV utility command.",
    "dbworkload/utils/tdigest.py": "Small adapter layer around tdigest centroid/value conversion.",
    "dbworkload/mcp/server.py": "MCP server exposing workload authoring docs and bounded workload execution tools.",
}

AGENT_RULES = [
    "Keep CLI argument parsing and Typer annotations in `dbworkload/cli/`; put command behavior in `dbworkload/commands/`.",
    "Prefer explicit imports or short module aliases over long fully-qualified calls in implementation code.",
    "Do not make runtime command code depend on CLI-only concerns; put shared data containers in neutral modules.",
    "Keep workload class loading behavior centralized in `dbworkload/utils/common.py` unless it is split into a dedicated import helper module.",
    "Keep generated user-facing docs under `docs/`; keep MCP-specific packaged docs under `dbworkload/mcp/`.",
    "Regenerate this file after package moves, entrypoint changes, or major command-flow changes.",
]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def public_defs(path: Path) -> tuple[list[str], list[str]]:
    tree = ast.parse(path.read_text(), filename=str(path))
    classes: list[str] = []
    functions: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and not node.name.startswith("_"):
            functions.append(node.name)

    return classes, functions


def module_rows() -> list[str]:
    rows = []
    for path in sorted(PACKAGE.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        name = rel(path)
        classes, functions = public_defs(path)
        symbols = []
        if classes:
            symbols.append("classes: " + ", ".join(classes))
        if functions:
            symbols.append("functions: " + ", ".join(functions))

        note = LAYER_NOTES.get(name, "")
        detail = "; ".join(symbols) if symbols else "no public classes/functions"
        if note:
            detail = f"{note} {detail}"

        rows.append(f"| `{name}` | {detail} |")
    return rows


def render() -> str:
    lines = [
        "# Code Map",
        "",
        "<!-- Generated by tools/generate_codemap.py. Do not edit by hand. -->",
        "",
        "This file is a compact guide for humans and LLM agents working in this repository.",
        "Regenerate it after structural code changes with:",
        "",
        "```bash",
        "python3 tools/generate_codemap.py",
        "```",
        "",
        "## Golden Flows",
        "",
        "- CLI run: `dbworkload.cli.main` -> `commands.run:run` -> supervisors -> workers -> workload class methods.",
        "- Connection setup: CLI `--uri` parsing -> `ConnInfo` -> command runtime `get_connection()`.",
        "- Utility commands: `dbworkload.cli.util` -> `dbworkload.commands.util` -> shared helpers/templates.",
        "- Conversion workflow: `dbworkload.cli.util cli_convert` -> `ConvertTool` -> prompts/providers -> generated/refined SQL.",
        "- MCP tools: `dbworkload.mcp.server` -> shell out to bounded `dbworkload run` invocations.",
        "",
        "## Entry Points",
        "",
        "- `dbworkload` -> `dbworkload.cli.main:app`",
        "- `dbworkload-mcp-server` -> `dbworkload.mcp.server:main`",
        "",
        "## Agent Rules",
        "",
    ]

    lines.extend(f"- {rule}" for rule in AGENT_RULES)
    lines.extend(
        [
            "",
            "## Modules",
            "",
            "| File | Purpose / Public Surface |",
            "| --- | --- |",
            *module_rows(),
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    content = render()
    if sys.argv[1:] == ["--check"]:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print("CODEMAP.md is out of date. Run: python3 tools/generate_codemap.py")
            raise SystemExit(1)
        return

    if sys.argv[1:]:
        print("Usage: python3 tools/generate_codemap.py [--check]")
        raise SystemExit(2)

    OUTPUT.write_text(content)


if __name__ == "__main__":
    main()
